name: 🐛 Bug Report
description: Found something wrong? Let us know!
title: "[Bug]: "
labels: ["bug", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible.
  - type: textarea
    id: description
    attributes:
      label: "🔍 Describe the Bug"
      description: "A clear and concise description of what the bug is."
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: "🔁 Steps To Reproduce"
      description: "Please provide detailed steps to reproduce the behavior."
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. See error
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: "✅ Expected Behavior"
      description: "What did you expect to happen?"
    validations:
      required: true
  - type: dropdown
    id: php-version
    attributes:
      label: "PHP Version"
      multiple: false
      options:
        - 8.3
        - 8.2
    validations:
      required: true
  - type: dropdown
    id: laravel-version
    attributes:
      label: "Laravel Version"
      multiple: false
      options:
        - "11.x"
        - "10.x"
    validations:
      required: true
  - type: textarea
    id: context
    attributes:
      label: "Additional Context"
      description: "Add any other context, screenshots, or logs about the problem here."